# Generated by Django 5.0.7 on 2024-07-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='aspect_sentiment',
            field=models.CharField(max_length=255),
        ),
    ]
